const ActionTypes = {
	ADD_ITEM: "ADD_ITEM",
	ADD_ITEM_SUCCESS: "ADD_ITEM_SUCCESS",
	ADD_ITEM_FAILED: "ADD_ITEM_FAILED",

	REMOVE_ITEM: "REMOVE_ITEM",
	REMOVE_ITEM_SUCCESS: "REMOVE_ITEM_SUCCESS",
	REMOVE_ITEM_FAILED: "REMOVE_ITEM_FAILED",

	FETCH_ITEMS_SUCCESS: "FETCH_ITEMS_SUCCESS",
	FETCH_ITEMS: "FETCH_ITEMS",
	FETCH_ITEMS_FAILED: "FETCH_ITEMS_FAILED",

	SET_CURRENCY: "SET_CURRENCY",
};

export { ActionTypes };
