const ActionTypes = {
	ADD_ITEM: "ADD_ITEM",
	ADD_ITEM_SUCCESS: "ADD_ITEM_SUCCESS",
	ADD_ITEM_FAILED: "ADD_ITEM_FAILED",
	SORT_ITEMS: "SORT_ITEMS",

	REMOVE_ITEM: "REMOVE_ITEM",
	REMOVE_ITEM_SUCCESS: "REMOVE_ITEM_SUCCESS",
	REMOVE_ITEM_FAILED: "REMOVE_ITEM_FAILED",

	FETCH_ITEMS_SUCCESS: "FETCH_ITEMS_SUCCESS",
	FETCH_ITEMS: "FETCH_ITEMS",
	FETCH_ITEMS_FAILED: "FETCH_ITEMS_FAILED",

	AUTH_START: "AUTH_START",
	AUTH_START_SUCCESS: "AUTH_START_SUCCESS",
	AUTH_START_FAILED: "AUTH_START_FAILED",
	AUTH_LOGOUT: "AUTH_LOGOUT",
	CLEAR_ERROR: "CLEAR_ERROR",
	PLAY_TUTORIAL: "PLAY_TUTORIAL",
	END_TUTORIAL: "END_TUTORIAL",

	USER_NAME_SUCCESS: "USER_NAME_SUCCESS",
	USER_NAME_FAILED: "USER_NAME_FAILED",

	SAVE_CHANGES_INIT: "SAVE_CHANGES_INIT",
	SAVE_CHANGES_SUCCESS: "SAVE_CHANGES_SUCCESS",
	SAVE_CHANGES_FAILED: "SAVE_CHANGES_FAILED",

	FETCH_SETTINGS_INIT: "FETCH_SETTINGS_INIT",
	FETCH_SETTINGS_SUCCESS: "FETCH_SETTINGS_SUCCESS",
	FETCH_SETTINGS_FAILED: "FETCH_SETTINGS_FAILED",

	ACTIVATE_WALLET_MODE: "ACTIVATE_WALLET_MODE",
	DEACTIVATE_WALLET_MODE: "DEACTIVATE_WALLET_MODE",
};

export { ActionTypes };
