const ActionTypes = {
	ADD_ITEM: "ADD_ITEM",
	ADD_ITEM_SUCCESS: "ADD_ITEM_SUCCESS",
	ADD_ITEM_FAILED: "ADD_ITEM_FAILED",

	REMOVE_ITEM: "REMOVE_ITEM",
	REMOVE_ITEM_SUCCESS: "REMOVE_ITEM_SUCCESS",
	REMOVE_ITEM_FAILED: "REMOVE_ITEM_FAILED",

	FETCH_ITEMS_SUCCESS: "FETCH_ITEMS_SUCCESS",
	FETCH_ITEMS: "FETCH_ITEMS",
	FETCH_ITEMS_FAILED: "FETCH_ITEMS_FAILED",

	SET_CURRENCY: "SET_CURRENCY",

	AUTH_START: "AUTH_START",
	AUTH_START_SUCCESS: "AUTH_START_SUCCESS",
	AUTH_START_FAILED: "AUTH_START_FAILED",
	AUTH_LOGOUT: "AUTH_LOGOUT",

	USER_NAME_SUCCESS: "USER_NAME_SUCCESS",
	USER_NAME_FAILED: "USER_NAME_FAILED",
};

export { ActionTypes };
